name: Ingestion Diaria Fichas de Cierre

on:
  schedule:
    - cron: '0 6 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: main
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug environment variables
      env: 
        BIG_BROTHER_WATCHING: ${{ vars.BIG_BROTHER_WATCHING }} 
        AUTH: ${{ secrets.AUTH }} 
        SHAREPOINT_URL: ${{ secrets.SHAREPOINT_URL }}
        
      run: |
        echo "AUTH is set: $([[ -n "$AUTH" ]] && echo "yes" || echo "no")"
        echo "SHAREPOINT_URL is set: $([[ -n "$SHAREPOINT_URL" ]] && echo "yes" || echo "no")"
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        
    - name: Run Python script
      env: 
        BIG_BROTHER_WATCHING: ${{ vars.BIG_BROTHER_WATCHING }} 
        AUTH: ${{ secrets.AUTH }} 
        SHAREPOINT_URL: ${{ secrets.SHAREPOINT_URL }}
        
      run: python ingestion.py
