name: Ingestion Diaria Fichas de Cierre

on:
  schedule:
    - cron: '0 6 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: sharepoint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        
    - name: Run Python script
      env: 
        # Variables
        BIG_BROTHER_WATCHING: ${{ vars.BIG_BROTHER_WATCHING }}
        CHARACTER_REPLACEMENTS: ${{ vars.CHARACTER_REPLACEMENTS }}
        VALID_CODE_PREFIXES: ${{ vars.VALID_CODE_PREFIXES }}
        MIN_CODE_LENGTH: ${{ vars.MIN_CODE_LENGTH }}
        SHAREPOINT_TARGET_FOLDERS: ${{ vars.SHAREPOINT_TARGET_FOLDERS }}
        SHAREPOINT_OBSERVED_PATH: ${{ vars.SHAREPOINT_OBSERVED_PATH }}
        SHAREPOINT_RECORDS_PATH: ${{ vars.SHAREPOINT_RECORDS_PATH }}
        
        # Secrets
        AUTH: ${{ secrets.AUTH }} 
        SHAREPOINT_ROOT_PATH: ${{ secrets.SHAREPOINT_ROOT_PATH }} 
        SHAREPOINT_URL: ${{ secrets.SHAREPOINT_URL }}
        
      run: python ingestion/ingestion.py
