name: Ingestion Diaria Fichas de Cierre

on:
  schedule:
    - cron: '0 6 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Python script
      run: python ingestion.py
      env: 
        BIG_BROTHER_WATCHING: ${{ vars.BIG_BROTHER_WATCHING }} 
        AUTH: ${{ secrets.AUTH }} 
        SHAREPOINT_URL: ${{ secrets.SHAREPOINT_URL }}
